USE [BD_UNBCDIGITAL]
GO

CREATE VIEW GFM_VW_NOTAS AS
WITH BASE AS (
    SELECT
        NOTA,
        TIPO_NOTA,
        TEXTO_BREVE,
        ORDEM,
        DATA_CRIACAO,
        CHAVE_CRIADOR_NOTA,
        GPM_NOTA,
        CENTRO_PLANEJAMENTO,
        CT_RESPONSAVEL,
        LOCAL_INSTALACAO,
        EQUIPAMENTO,
        CAMPO_SELECAO,
        STATUS_SISTEMA,
        STATUS_USUARIO,
        DATA_ENCERRAMENTO,
        DATA_ULTIMA_MODIFICACAO,
        DATA_FIM_DESEJADO,
        TIPO_INTERVENCAO,
        DATA_HORA_ATUALIZACAO_ODS,
        
        -- Lógica para definir NOVA_DATA_ENCE
        CASE
            WHEN DATA_ENCERRAMENTO IS NULL 
                 AND (CHARINDEX('MREL', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
                      OR CHARINDEX('MSEN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0) 
            THEN DATA_ULTIMA_MODIFICACAO
            WHEN DATA_ENCERRAMENTO IS NULL THEN DATA_ULTIMA_MODIFICACAO
            ELSE DATA_ENCERRAMENTO
        END AS NOVA_DATA_ENCE
    FROM [BD_UNBCDIGITAL].[biin].[nota_manutencao]
    WHERE TIPO_NOTA <> 'ZR'
)
SELECT
    NOTA AS NOTA_NR,
    TIPO_NOTA AS NOTA_TIPO,
    'Nota: ' + TEXTO_BREVE AS DESCRICAO,
    ORDEM,
    DATA_CRIACAO AS DT_CRIACAO,
    CHAVE_CRIADOR_NOTA AS CRIADO_POR,
    GPM_NOTA + '-' + CENTRO_PLANEJAMENTO AS COD_RESP,
    CT_RESPONSAVEL + '-' + CENTRO_PLANEJAMENTO AS COD_CT_RESP,
    LOCAL_INSTALACAO AS LOC_INST,
    LEFT(LOCAL_INSTALACAO, 6) AS COD_PLAT,
    SUBSTRING(LOCAL_INSTALACAO, CHARINDEX('.', LOCAL_INSTALACAO) + 1, 4) AS COD_SIST,
    EQUIPAMENTO AS EQUIP,
    CAMPO_SELECAO as CRIT_SELEC,
    STATUS_SISTEMA + ' ' + STATUS_USUARIO AS STATUS,
    DATA_ENCERRAMENTO AS DATA_ENCE,
    NOVA_DATA_ENCE,
    DATA_FIM_DESEJADO AS DT_VENC,
    TIPO_INTERVENCAO,

    CASE 
        WHEN CHARINDEX('MREL', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN '6 - ELIMINADA'
        WHEN CHARINDEX('MSEN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN '5 - QUITADA/ENCERRADA'
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 AND ORDEM IS NOT NULL THEN '4 - ORDEM GERADA'
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND CHARINDEX('TRIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) = 0 
             AND CHARINDEX('SUSP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) = 0 
        THEN '1 - AVALIAR/TRIAR NOTA'
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND CHARINDEX('SUSP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
        THEN '2 - SUSPENSA'
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN '3 - TRIADA/GERAR ORDEM'
        WHEN CHARINDEX('MSPN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             OR CHARINDEX('MSDI', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
        THEN '0 - AGUARD.LIB/APROV'
        ELSE 'VERIFICAR'
    END AS SIT_NOTAS,

    -- MUDANÇA: PEND, QUIT e CANC agora usam NOVA_DATA_ENCE
    CASE WHEN NOVA_DATA_ENCE IS NULL THEN 1 ELSE 0 END AS PEND,
    CASE WHEN NOVA_DATA_ENCE IS NOT NULL 
              AND (STATUS_SISTEMA + ' ' + STATUS_USUARIO) NOT LIKE '%MREL%' 
              AND (STATUS_SISTEMA + ' ' + STATUS_USUARIO) NOT LIKE '%MSEN%' 
         THEN 1 ELSE 0 END AS QUIT,
    CASE WHEN NOVA_DATA_ENCE IS NOT NULL 
              AND ((STATUS_SISTEMA + ' ' + STATUS_USUARIO) LIKE '%MREL%' 
                   OR (STATUS_SISTEMA + ' ' + STATUS_USUARIO) LIKE '%MSEN%') 
         THEN 1 ELSE 0 END AS CANC,

    CASE WHEN CHARINDEX('IMED', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
              OR CHARINDEX('PRIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS IMED_PRIA,
    CASE WHEN CHARINDEX('IMPD', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS IMPD,

    CASE
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND CHARINDEX('TRIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) = 0 
             AND CHARINDEX('SUSP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND ORDEM IS NULL THEN 1 ELSE 0
    END AS SUSP,

    CASE
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND CHARINDEX('TRIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND CHARINDEX('SUSP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND ORDEM IS NULL THEN 1 ELSE 0
    END AS INC1,

    CASE
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND CHARINDEX('TRIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) = 0 
             AND CHARINDEX('SUSP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) = 0 
             AND ORDEM IS NOT NULL THEN 1 ELSE 0
    END AS INC2,

    CASE
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND CHARINDEX('TRIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) = 0 
             AND CHARINDEX('SUSP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
             AND ORDEM IS NOT NULL THEN 1 ELSE 0
    END AS INC3,

    CASE
        WHEN CHARINDEX('LUCA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0
             OR CHARINDEX('LUPA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0
             OR CHARINDEX('PPRO', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0
             OR CHARINDEX('SUMS', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0
    END AS PARADA_UMS,

    CASE 
        WHEN CHARINDEX('CNTN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Contingenciamento Não Necessário'
        WHEN CHARINDEX('CONT', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Contingenciado/Análise Cont'
        WHEN CHARINDEX('CNTS', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Contingenciamento Necessário'
        WHEN CHARINDEX('CNTA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Avaliar Nec. Contingenciamento'
        ELSE NULL 
    END AS CONTINGENCIAMENTO,

    DATA_HORA_ATUALIZACAO_ODS AS ULTIMA_CARGA_ODS
FROM BASE;